# ─── SENTINEL Alert Model ─────────────────────────────────────────────────────
# Stores AI-generated alerts with Explainable AI (XAI/SHAP) explanations.
# Created automatically when a high-risk event is detected.

import uuid
from datetime import datetime, timezone
from sqlalchemy import String, Integer, DateTime, Text, ForeignKey, Boolean
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.config.database import Base


def _now() -> datetime:
    return datetime.now(timezone.utc)


class Alert(Base):
    """
    Security alerts generated by the Risk Engine or ML model.

    Each alert explains WHY it was flagged (XAI explanation stored as JSON).
    An admin can resolve or dismiss alerts.

    Relationships:
        - Belongs to one User (the account at risk)
        - Linked to one Event (the raw event that triggered it)
        - Optionally resolved by one User (admin)
    """
    __tablename__ = "alerts"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )

    # ── Ownership ─────────────────────────────────────────────────────────────
    user_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    event_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("events.id", ondelete="SET NULL"), nullable=True
    )

    # ── Alert Content ─────────────────────────────────────────────────────────
    title:       Mapped[str]       = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)

    # ── Classification ────────────────────────────────────────────────────────
    type:        Mapped[str] = mapped_column(String(50), nullable=False)
    # Values: "fraud" | "intrusion" | "login" | "transaction"

    severity:    Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    # Values: "low" | "medium" | "high" | "critical"

    status:      Mapped[str] = mapped_column(String(20), default="open", index=True)
    # Values: "open" | "resolved" | "dismissed"

    # ── Risk Details ──────────────────────────────────────────────────────────
    risk_score:  Mapped[int]       = mapped_column(Integer, default=0)
    ip_address:  Mapped[str | None] = mapped_column(String(50))
    location:    Mapped[str | None] = mapped_column(String(100))
    device:      Mapped[str | None] = mapped_column(String(150))

    # ── Explainable AI (XAI) ─────────────────────────────────────────────────
    # JSON array: [{"factor": "Unusual location", "contribution": 0.35, "direction": "positive"}, ...]
    # Positive = increases risk, Negative = decreases risk
    shap_values:     Mapped[str | None] = mapped_column(Text)  # JSON
    recommendation:  Mapped[str | None] = mapped_column(Text)

    # ── Resolution ────────────────────────────────────────────────────────────
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    resolved_by: Mapped[str | None]      = mapped_column(String(36), ForeignKey("users.id"))

    # ── Timestamps ────────────────────────────────────────────────────────────
    created_at:  Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, index=True)

    # ── Relationships ─────────────────────────────────────────────────────────
    user:     Mapped["User"]         = relationship("User",  back_populates="alerts", foreign_keys=[user_id])  # type: ignore[name-defined]
    event:    Mapped["Event | None"] = relationship("Event", back_populates="alert")  # type: ignore[name-defined]

    def __repr__(self) -> str:
        return f"<Alert id={self.id!r} severity={self.severity!r} status={self.status!r}>"
